### ISSUE TITLE
 parameterized names for the configmaps "project-monitoring-rancher-default-dashboards" and "nginx-proxy-config-project-monitoring-grafana"

### ISSUE THREAD

**Issue by RonaldHuse** [caas-team/caas-project-monitoring#37]
We would like to temporarily run multiple instances of monitoring in a namespace. (feature and develop branch)

This would require that the part of the name "project-monitoring" not be implemented hard-coded in the templates for "grafana-nginx-config.yaml" and "grafana-dashboards.yaml", but rather from the values ​​from e.g. kube-prometheus-stack.nameOverride or kube -prometheus stack. fullnameOverride is taken.

**Comment by eumel8** [comment]
We have this name "project-monitoring" on multiple places hard-codes due the constraints in Rancher where we need for the dashboard static names to create the [NavLinks](https://github.com/eumel8/navlinkswebhook/blob/ae2ee508b8fc702e8fef56716e9eb31d8fc9fadb/navlinkswebhook.go#L150) project-based in Rancher UI. Multiple installation in the same namespace is completely unsupported at this time. You can build your own fork and expose service endpoints with Ingress. But the Rancher integration will not work. 
Cc @puffitos

**Comment by puffitos** [comment]
Like @eumel8 said, naming is a crux he have to carry. Would encourage you to build your one prometheus installation to monitor your different application states, instead of deploying a whole new copy of the prometheus stack.

Or is there some reason why you want to deploy project monitoring twice?

**Comment by RonaldHuse** [comment]
The reason is just our current deployment process. If we make a configuration change to monitoring in Gitlab via a feature branch, then it is rolled out in the same namespace as the develop/master variant.
Since I was not aware of the problem with Rancher, the issue can be closed.
I'll check whether we move the feature branches to a different namespace or temporarily uninstall monitoring from develop/master if we want to change something.
Thank you!
